// SPDX-FileCopyrightText: The respective FFmpeg copyright holders; see UPSTREAM-COPYRIGHTS.txt
// SPDX-FileCopyrightText: 2026 Ffmpeg.CsPort.Decoder contributors
// SPDX-License-Identifier: LGPL-2.1-or-later AND BSL-1.0
/*
 * This file is part of Ffmpeg.CsPort.Decoder, an independent C# port of FFmpeg.
 *
 * This file belongs to a C# translation and modified work of FFmpeg source code from commit
 * 9b6c8969e05b4f0b29f0f85cd501be6b3e582e6b:
 * https://github.com/FFmpeg/FFmpeg/tree/9b6c8969e05b4f0b29f0f85cd501be6b3e582e6b
 * The exact upstream-file mapping and the original copyright notices are recorded in
 * PORTED-FROM-FFMPEG.md and UPSTREAM-COPYRIGHTS.txt.
 *
 * Created or modified 2026-08-06: translated from C to C# or added as managed port support.
 *
 * This library is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation; either version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 * PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License along with
 * this library. If not, see <https://www.gnu.org/licenses/>.
 *
 * PORT-NOTE: 1:1 translation. Do not refactor, reorder, or simplify; bit-exactness
 * against the FFmpeg reference is verified by the conformance tests.
 */
/*
 * The Bessel function implementation is derived from Boost and remains subject
 * to the Boost Software License, Version 1.0 (August 17th, 2003):
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */
using System;
using System.Runtime.CompilerServices;

namespace Ffmpeg.CsPort.Decoder.Mathematics
{
	/// <summary>
	/// Ports the integer, clipping, rational, rescaling, and Bessel operations shared by FFmpeg audio components.
	/// </summary>
	internal static class FfmpegMath
	{
		private static readonly double[] s_BesselP1 =
		{
			-2.2335582639474375249e+15, -5.5050369673018427753e+14, -3.2940087627407749166e+13,
			-8.4925101247114157499e+11, -1.1912746104985237192e+10, -1.0313066708737980747e+08,
			-5.9545626019847898221e+05, -2.4125195876041896775e+03, -7.0935347449210549190e+00,
			-1.5453977791786851041e-02, -2.5172644670688975051e-05, -3.0517226450451067446e-08,
			-2.6843448573468483278e-11, -1.5982226675653184646e-14, -5.2487866627945699800e-18
		};

		private static readonly double[] s_BesselQ1 =
		{
			-2.2335582639474375245e+15, 7.8858692566751002988e+12, -1.2207067397808979846e+10,
			1.0377081058062166144e+07, -4.8527560179962773045e+03, 1.0
		};

		private static readonly double[] s_BesselP2 =
		{
			-2.2210262233306573296e-04, 1.3067392038106924055e-02, -4.4700805721174453923e-01,
			5.5674518371240761397e+00, -2.3517945679239481621e+01, 3.1611322818701131207e+01,
			-9.6090021968656180000e+00
		};

		private static readonly double[] s_BesselQ2 =
		{
			-5.5194330231005480228e-04, 3.2547697594819615062e-02, -1.1151759188741312645e+00,
			1.3982595353892851542e+01, -6.0228002066743340583e+01, 8.5539563258012929600e+01,
			-3.1446690275135491500e+01, 1.0
		};

		private static readonly ulong[] s_Exp2FloatScale =
		{
			0x3FF0000000000000UL, 0x3FEFD9B0D3158574UL, 0x3FEFB5586CF9890FUL, 0x3FEF9301D0125B51UL,
			0x3FEF72B83C7D517BUL, 0x3FEF54873168B9AAUL, 0x3FEF387A6E756238UL, 0x3FEF1E9DF51FDEE1UL,
			0x3FEF06FE0A31B715UL, 0x3FEEF1A7373AA9CBUL, 0x3FEEDEA64C123422UL, 0x3FEECE086061892DUL,
			0x3FEEBFDAD5362A27UL, 0x3FEEB42B569D4F82UL, 0x3FEEAB07DD485429UL, 0x3FEEA47EB03A5585UL,
			0x3FEEA09E667F3BCDUL, 0x3FEE9F75E8EC5F74UL, 0x3FEEA11473EB0187UL, 0x3FEEA589994CCE13UL,
			0x3FEEACE5422AA0DBUL, 0x3FEEB737B0CDC5E5UL, 0x3FEEC49182A3F090UL, 0x3FEED503B23E255DUL,
			0x3FEEE89F995AD3ADUL, 0x3FEEFF76F2FB5E47UL, 0x3FEF199BDD85529CUL, 0x3FEF3720DCEF9069UL,
			0x3FEF5818DCFBA487UL, 0x3FEF7C97337B9B5FUL, 0x3FEFA4AFA2A490DAUL, 0x3FEFD0765B6E4540UL
		};

		public static int Absolute(int value)
		{
			return value >= 0 ? value : unchecked(-value);
		}

		public static long Absolute(long value)
		{
			return value >= 0 ? value : unchecked(-value);
		}

		public static uint AbsoluteUnsigned(int value)
		{
			return value <= 0 ? unchecked(0U - (uint)value) : (uint)value;
		}

		public static ulong AbsoluteUnsigned(long value)
		{
			return value <= 0 ? unchecked(0UL - (ulong)value) : (ulong)value;
		}

		public static int RoundedRightShift(int value, int bitCount)
		{
			var rounding = (1 << bitCount) >> 1;
			return value > 0 ? value + rounding >> bitCount : value + rounding - 1 >> bitCount;
		}

		public static int RoundedDivide(int value, int divisor)
		{
			return value >= 0 ? (value + (divisor >> 1)) / divisor : (value - (divisor >> 1)) / divisor;
		}

		public static int CeilRightShift(int value, int bitCount)
		{
			return (value + (1 << bitCount) - 1) >> bitCount;
		}

		public static int UnsignedDivide(int value, int divisor)
		{
			return (value > 0 ? value : value - divisor + 1) / divisor;
		}

		public static int UnsignedModulo(int value, int divisor)
		{
			return value - divisor * UnsignedDivide(value, divisor);
		}

		public static int Clip(int value, int minimum, int maximum)
		{
			if (value < minimum)
			{
				return minimum;
			} else if (value > maximum)
			{
				return maximum;
			}

			return value;
		}

		public static long Clip(long value, long minimum, long maximum)
		{
			if (value < minimum)
			{
				return minimum;
			} else if (value > maximum)
			{
				return maximum;
			}

			return value;
		}

		public static byte ClipUnsigned8(int value)
		{
			return (value & ~0xff) != 0 ? (byte)((~value) >> 31) : (byte)value;
		}

		public static sbyte ClipSigned8(int value)
		{
			return ((unchecked((uint)value + 0x80U) & ~0xffU) != 0)
				? (sbyte)((value >> 31) ^ 0x7f)
				: (sbyte)value;
		}

		public static ushort ClipUnsigned16(int value)
		{
			return (value & ~0xffff) != 0 ? (ushort)((~value) >> 31) : (ushort)value;
		}

		public static short ClipSigned16(int value)
		{
			return ((unchecked((uint)value + 0x8000U) & ~0xffffU) != 0)
				? (short)((value >> 31) ^ 0x7fff)
				: (short)value;
		}

		public static int ClipSigned32(long value)
		{
			var unsignedValue = unchecked((ulong)value + 0x80000000UL);
			return (unsignedValue & ~0xffffffffUL) != 0
				? (int)((value >> 63) ^ 0x7fffffff)
				: (int)value;
		}

		public static int ClipSignedPowerOfTwo(int value, int power)
		{
			if ((unchecked((uint)value + (1U << power)) & ~((2U << power) - 1)) != 0)
			{
				return (value >> 31) ^ ((1 << power) - 1);
			}

			return value;
		}

		public static uint ClipUnsignedPowerOfTwo(int value, int power)
		{
			var mask = (1U << power) - 1;
			return (unchecked((uint)value) & ~mask) != 0 ? unchecked((uint)~value) >> 31 & mask : (uint)value;
		}

		public static uint ZeroExtend(uint value, int bits)
		{
			return value & ((1U << bits) - 1);
		}

		public static int SignExtend(uint value, int bits)
		{
			var shift = 32 - bits;
			return unchecked((int)(value << shift)) >> shift;
		}

		public static long SignExtend64(ulong value, int bits)
		{
			var shift = 64 - bits;
			return unchecked((long)(value << shift)) >> shift;
		}

		public static int SaturatingAdd32(int first, int second)
		{
			return ClipSigned32((long)first + second);
		}

		public static int SaturatingSubtract32(int first, int second)
		{
			return ClipSigned32((long)first - second);
		}

		public static long SaturatingAdd64(long first, long second)
		{
			var sum = unchecked((long)(unchecked((ulong)first) + unchecked((ulong)second)));
			if ((first ^ second | ~sum ^ second) >= 0)
			{
				return long.MaxValue ^ (second >> 63);
			}

			return sum;
		}

		public static long SaturatingSubtract64(long first, long second)
		{
			if (second <= 0 && first >= long.MaxValue + second)
			{
				return long.MaxValue;
			}
			if (second >= 0 && first <= long.MinValue + second)
			{
				return long.MinValue;
			}

			return first - second;
		}

		public static int SaturatingDoubleAdd32(int first, int second)
		{
			return SaturatingAdd32(first, SaturatingAdd32(second, second));
		}

		public static int SaturatingDoubleSubtract32(int first, int second)
		{
			return SaturatingSubtract32(first, SaturatingAdd32(second, second));
		}

		public static float Clip(float value, float minimum, float maximum)
		{
			var lowerClipped = value > minimum ? value : minimum;
			return lowerClipped > maximum ? maximum : lowerClipped;
		}

		/// <summary>Forces the scalar C path's float rounding boundary before a following addition can be fused by the JIT.</summary>
		[MethodImpl(MethodImplOptions.NoInlining)]
		public static float MultiplyFloat(float first, float second)
		{
			return first * second;
		}

		public static double Clip(double value, double minimum, double maximum)
		{
			var lowerClipped = value > minimum ? value : minimum;
			return lowerClipped > maximum ? maximum : lowerClipped;
		}

		public static int Log2(uint value)
		{
			var result = 0;
			if ((value & 0xffff0000U) != 0)
			{
				value >>= 16;
				result += 16;
			}
			if ((value & 0xff00U) != 0)
			{
				value >>= 8;
				result += 8;
			}

			return result + Log2Byte((byte)value);
		}

		public static int CountTrailingZeros(ulong value)
		{
			if (value == 0)
			{
				return 64;
			}

			var count = 0;
			while ((value & 1) == 0)
			{
				value >>= 1;
				count++;
			}

			return count;
		}

		public static int CountTrailingZeros(uint value)
		{
			if (value == 0)
			{
				return 32;
			}

			var count = 0;
			while ((value & 1) == 0)
			{
				value >>= 1;
				count++;
			}

			return count;
		}

		public static int CountLeadingZeros(uint value)
		{
			var count = 32;
			while (value != 0)
			{
				value >>= 1;
				count--;
			}

			return count;
		}

		public static int CeilLog2(int value)
		{
			return Log2(unchecked((uint)(value - 1) << 1));
		}

		public static int PopCount(ulong value)
		{
			return PopCount((uint)value) + PopCount((uint)(value >> 32));
		}

		public static int PopCount(uint value)
		{
			value -= (value >> 1) & 0x55555555U;
			value = (value & 0x33333333U) + ((value >> 2) & 0x33333333U);
			value = (value + (value >> 4)) & 0x0f0f0f0fU;
			value += value >> 8;
			return (int)((value + (value >> 16)) & 0x3fU);
		}

		public static int Parity(uint value)
		{
			return PopCount(value) & 1;
		}

		public static long Gcd(long first, long second)
		{
			if (first == 0)
			{
				return second;
			}
			if (second == 0)
			{
				return first;
			}

			var firstZeros = CountTrailingZeros(unchecked((ulong)first));
			var secondZeros = CountTrailingZeros(unchecked((ulong)second));
			var commonZeros = Math.Min(firstZeros, secondZeros);
			var firstValue = Absolute(first >> firstZeros);
			var secondValue = Absolute(second >> secondZeros);
			while (firstValue != secondValue)
			{
				if (firstValue > secondValue)
				{
					var temporary = secondValue;
					secondValue = firstValue;
					firstValue = temporary;
				}
				secondValue -= firstValue;
				secondValue >>= CountTrailingZeros((ulong)secondValue);
			}

			return unchecked((long)((ulong)firstValue << commonZeros));
		}

		/// <summary>
		/// Preserves FFmpeg's split 64-bit multiply/divide path and every rounding branch of av_rescale_rnd.
		/// </summary>
		public static long RescaleRounding(long value, long multiplier, long divisor, AvRounding rounding)
		{
			long roundingOffset = 0;
			var baseRounding = rounding & ~AvRounding.PassMinMax;
			if (divisor <= 0 || multiplier < 0 || (uint)baseRounding > 5 || baseRounding == (AvRounding)4)
			{
				return long.MinValue;
			}

			if ((rounding & AvRounding.PassMinMax) != 0)
			{
				if (value == long.MinValue || value == long.MaxValue)
				{
					return value;
				}
				rounding -= AvRounding.PassMinMax;
			}

			if (value < 0)
			{
				var positiveValue = unchecked(-Math.Max(value, -long.MaxValue));
				var inverseRounding = rounding ^ (AvRounding)(((int)rounding >> 1) & 1);
				return unchecked((long)(0UL - (ulong)RescaleRounding(positiveValue, multiplier, divisor, inverseRounding)));
			}

			if (rounding == AvRounding.NearInfinity)
			{
				roundingOffset = divisor / 2;
			} else if (((int)rounding & 1) != 0)
			{
				roundingOffset = divisor - 1;
			}

			if (multiplier <= int.MaxValue && divisor <= int.MaxValue)
			{
				if (value <= int.MaxValue)
				{
					return (value * multiplier + roundingOffset) / divisor;
				}

				var dividedValue = value / divisor;
				var remainder = (value % divisor * multiplier + roundingOffset) / divisor;
				if (dividedValue >= int.MaxValue && multiplier != 0 && dividedValue > (long.MaxValue - remainder) / multiplier)
				{
					return long.MinValue;
				}

				return dividedValue * multiplier + remainder;
			}

			var valueLow = (ulong)value & 0xffffffffUL;
			var valueHigh = (ulong)value >> 32;
			var multiplierLow = (ulong)multiplier & 0xffffffffUL;
			var multiplierHigh = (ulong)multiplier >> 32;
			var quotient = unchecked(valueLow * multiplierHigh + valueHigh * multiplierLow);
			var shiftedProduct = unchecked(quotient << 32);
			valueLow = unchecked(valueLow * multiplierLow + shiftedProduct);
			valueHigh = unchecked(valueHigh * multiplierHigh + (quotient >> 32) + (valueLow < shiftedProduct ? 1UL : 0UL));
			var unsignedOffset = (ulong)roundingOffset;
			valueLow = unchecked(valueLow + unsignedOffset);
			valueHigh = unchecked(valueHigh + (valueLow < unsignedOffset ? 1UL : 0UL));

			for (var index = 63; index >= 0; index--)
			{
				valueHigh = unchecked(valueHigh + valueHigh + ((valueLow >> index) & 1));
				quotient = unchecked(quotient + quotient);
				if ((ulong)divisor <= valueHigh)
				{
					valueHigh -= (ulong)divisor;
					quotient++;
				}
			}
			if (quotient > long.MaxValue)
			{
				return long.MinValue;
			}

			return (long)quotient;
		}

		public static long Rescale(long value, long multiplier, long divisor)
		{
			return RescaleRounding(value, multiplier, divisor, AvRounding.NearInfinity);
		}

		public static long RescaleRational(long value, AvRational source, AvRational destination, AvRounding rounding = AvRounding.NearInfinity)
		{
			var multiplier = source.Numerator * (long)destination.Denominator;
			var divisor = destination.Numerator * (long)source.Denominator;
			return RescaleRounding(value, multiplier, divisor, rounding);
		}

		/// <summary>
		/// Reduces or continued-fraction-approximates a rational within FFmpeg's signed integer bound.
		/// </summary>
		public static bool Reduce(out int destinationNumerator, out int destinationDenominator, long numerator, long denominator, long maximum)
		{
			var first = new AvRational(0, 1);
			var second = new AvRational(1, 0);
			var negative = (numerator < 0) ^ (denominator < 0);
			var divisor = Gcd(Absolute(numerator), Absolute(denominator));
			if (divisor != 0)
			{
				numerator = Absolute(numerator) / divisor;
				denominator = Absolute(denominator) / divisor;
			}
			if (numerator <= maximum && denominator <= maximum)
			{
				second = new AvRational((int)numerator, (int)denominator);
				denominator = 0;
			}

			while (denominator != 0)
			{
				var factor = (ulong)(numerator / denominator);
				var nextDenominator = numerator - denominator * (long)factor;
				var nextNumerator = (long)factor * second.Numerator + first.Numerator;
				var nextRationalDenominator = (long)factor * second.Denominator + first.Denominator;
				if (nextNumerator > maximum || nextRationalDenominator > maximum)
				{
					if (second.Numerator != 0)
					{
						factor = (ulong)((maximum - first.Numerator) / second.Numerator);
					}
					if (second.Denominator != 0)
					{
						factor = Math.Min(factor, (ulong)((maximum - first.Denominator) / second.Denominator));
					}
					if (denominator * (2 * (long)factor * second.Denominator + first.Denominator) > numerator * second.Denominator)
					{
						second = new AvRational(
							(int)((long)factor * second.Numerator + first.Numerator),
							(int)((long)factor * second.Denominator + first.Denominator));
					}
					break;
				}

				first = second;
				second = new AvRational((int)nextNumerator, (int)nextRationalDenominator);
				numerator = denominator;
				denominator = nextDenominator;
			}

			destinationNumerator = negative ? -second.Numerator : second.Numerator;
			destinationDenominator = second.Denominator;
			return denominator == 0;
		}

		public static AvRational Multiply(AvRational first, AvRational second)
		{
			Reduce(out first.Numerator, out first.Denominator,
				first.Numerator * (long)second.Numerator,
				first.Denominator * (long)second.Denominator,
				int.MaxValue);
			return first;
		}

		public static AvRational Divide(AvRational first, AvRational second)
		{
			return Multiply(first, new AvRational(second.Denominator, second.Numerator));
		}

		public static AvRational Add(AvRational first, AvRational second)
		{
			Reduce(out first.Numerator, out first.Denominator,
				first.Numerator * (long)second.Denominator + second.Numerator * (long)first.Denominator,
				first.Denominator * (long)second.Denominator,
				int.MaxValue);
			return first;
		}

		public static AvRational Subtract(AvRational first, AvRational second)
		{
			return Add(first, new AvRational(-second.Numerator, second.Denominator));
		}

		public static AvRational FromDouble(double value, int maximum)
		{
			if (double.IsNaN(value))
			{
				return new AvRational(0, 0);
			}
			if (Math.Abs(value) > int.MaxValue + 3L)
			{
				return new AvRational(value < 0 ? -1 : 1, 0);
			}

			var exponent = value == 0 ? 0 : Math.ILogB(value) + 1;
			exponent = Math.Max(exponent - 1, 0);
			var denominator = 1L << (62 - exponent);
			Reduce(out var numerator, out var reducedDenominator,
				(long)Math.Floor(value * denominator + 0.5), denominator, maximum);
			return new AvRational(numerator, reducedDenominator);
		}

		public static int Nearer(AvRational value, AvRational first, AvRational second)
		{
			var numerator = first.Numerator * (long)second.Denominator + second.Numerator * (long)first.Denominator;
			var denominator = 2 * (long)first.Denominator * second.Denominator;
			var upper = RescaleRounding(numerator, value.Denominator, denominator, AvRounding.Up);
			var lower = RescaleRounding(numerator, value.Denominator, denominator, AvRounding.Down);
			return ((upper > value.Numerator ? 1 : 0) - (lower < value.Numerator ? 1 : 0)) * second.Compare(first);
		}

		public static int FindNearestIndex(AvRational value, AvRational[] values)
		{
			var nearestIndex = 0;
			for (var index = 0; values[index].Denominator != 0; index++)
			{
				if (Nearer(value, values[index], values[nearestIndex]) > 0)
				{
					nearestIndex = index;
				}
			}

			return nearestIndex;
		}

		public static uint RationalToIntFloat(AvRational value)
		{
			if (value.Denominator < 0)
			{
				value.Denominator *= -1;
				value.Numerator *= -1;
			}
			var sign = 0;
			if (value.Numerator < 0)
			{
				value.Numerator *= -1;
				sign = 1;
			}
			if (value.Numerator == 0 && value.Denominator == 0)
			{
				return 0xffc00000U;
			}
			if (value.Numerator == 0)
			{
				return 0;
			}
			if (value.Denominator == 0)
			{
				return 0x7f800000U | ((uint)value.Numerator & 0x80000000U);
			}

			var shift = 23 + Log2((uint)value.Denominator) - Log2((uint)value.Numerator);
			long scaled = shift >= 0
				? Rescale(value.Numerator, 1L << shift, value.Denominator)
				: Rescale(value.Numerator, 1, (long)value.Denominator << -shift);
			shift -= scaled >= 1 << 24 ? 1 : 0;
			shift += scaled < 1 << 23 ? 1 : 0;
			scaled = shift >= 0
				? Rescale(value.Numerator, 1L << shift, value.Denominator)
				: Rescale(value.Numerator, 1, (long)value.Denominator << -shift);
			return (uint)(sign << 31 | (150 - shift) << 23 | (int)(scaled - (1 << 23)));
		}

		public static AvRational Gcd(AvRational first, AvRational second, int maximumDenominator, AvRational defaultValue)
		{
			var divisor = Gcd(first.Denominator, second.Denominator);
			var leastCommonMultiple = first.Denominator / divisor * second.Denominator;
			return leastCommonMultiple < maximumDenominator
				? new AvRational((int)Gcd(first.Numerator, second.Numerator), (int)leastCommonMultiple)
				: defaultValue;
		}

		public static int CompareTimestamps(long firstTimestamp, AvRational firstTimeBase, long secondTimestamp, AvRational secondTimeBase)
		{
			var firstScale = firstTimeBase.Numerator * (long)secondTimeBase.Denominator;
			var secondScale = secondTimeBase.Numerator * (long)firstTimeBase.Denominator;
			if ((AbsoluteUnsigned(firstTimestamp) | (ulong)firstScale | AbsoluteUnsigned(secondTimestamp) | (ulong)secondScale) <= int.MaxValue)
			{
				var firstValue = firstTimestamp * firstScale;
				var secondValue = secondTimestamp * secondScale;
				return (firstValue > secondValue ? 1 : 0) - (firstValue < secondValue ? 1 : 0);
			}
			if (RescaleRounding(firstTimestamp, firstScale, secondScale, AvRounding.Down) < secondTimestamp)
			{
				return -1;
			}
			if (RescaleRounding(secondTimestamp, secondScale, firstScale, AvRounding.Down) < firstTimestamp)
			{
				return 1;
			}

			return 0;
		}

		public static long CompareModulo(ulong first, ulong second, ulong modulo)
		{
			var difference = unchecked((long)((first - second) & (modulo - 1)));
			if (difference > (long)(modulo >> 1))
			{
				difference -= (long)modulo;
			}

			return difference;
		}

		public static long RescaleDelta(AvRational inputTimeBase, long inputTimestamp, AvRational sampleTimeBase,
			int duration, ref long last, AvRational outputTimeBase)
		{
			if (last == long.MinValue || duration == 0 ||
				inputTimeBase.Numerator * (long)outputTimeBase.Denominator <= outputTimeBase.Numerator * (long)inputTimeBase.Denominator)
			{
				last = RescaleRational(inputTimestamp, inputTimeBase, sampleTimeBase) + duration;
				return RescaleRational(inputTimestamp, inputTimeBase, outputTimeBase);
			}

			var lower = RescaleRational(2 * inputTimestamp - 1, inputTimeBase, sampleTimeBase, AvRounding.Down) >> 1;
			var upper = (RescaleRational(2 * inputTimestamp + 1, inputTimeBase, sampleTimeBase, AvRounding.Up) + 1) >> 1;
			if (last < 2 * lower - upper || last > 2 * upper - lower)
			{
				last = RescaleRational(inputTimestamp, inputTimeBase, sampleTimeBase) + duration;
				return RescaleRational(inputTimestamp, inputTimeBase, outputTimeBase);
			}

			var current = Clip(last, lower, upper);
			last = current + duration;
			return RescaleRational(current, sampleTimeBase, outputTimeBase);
		}

		public static long AddStable(AvRational timestampTimeBase, long timestamp, AvRational incrementTimeBase, long increment)
		{
			if (increment != 1)
			{
				incrementTimeBase = Multiply(incrementTimeBase, new AvRational((int)increment, 1));
			}

			var multiplier = incrementTimeBase.Numerator * (long)timestampTimeBase.Denominator;
			var divisor = incrementTimeBase.Denominator * (long)timestampTimeBase.Numerator;
			if (multiplier % divisor == 0 && timestamp <= long.MaxValue - multiplier / divisor)
			{
				return timestamp + multiplier / divisor;
			}
			if (multiplier < divisor)
			{
				return timestamp;
			}

			var old = RescaleRational(timestamp, timestampTimeBase, incrementTimeBase);
			var oldTimestamp = RescaleRational(old, incrementTimeBase, timestampTimeBase);
			if (old == long.MaxValue || old == long.MinValue || oldTimestamp == long.MinValue)
			{
				return timestamp;
			}

			return SaturatingAdd64(RescaleRational(old + 1, incrementTimeBase, timestampTimeBase), timestamp - oldTimestamp);
		}

		public static double BesselI0(double value)
		{
			if (value == 0)
			{
				return 1.0;
			}
			value = Math.Abs(value);
			if (value <= 15)
			{
				var squared = value * value;
				return EvaluatePolynomial(s_BesselP1, squared) / EvaluatePolynomial(s_BesselQ1, squared);
			}

			var inverse = 1 / value - 1.0 / 15;
			var ratio = EvaluatePolynomial(s_BesselP2, inverse) / EvaluatePolynomial(s_BesselQ2, inverse);
			var factor = Math.Exp(value) / Math.Sqrt(value);
			return factor * ratio;
		}

		/// <summary>Preserves the scalar exp2f range reduction, polynomial schedule, and final float rounding used by the reference build.</summary>
		public static float Exp2Float(float value)
		{
			if (value < -126.0f || value >= 128.0f || !float.IsFinite(value)) return float.Exp2(value);
			const double rounding = 211106232532992.0;
			var input = (double)value;
			var roundedWithMagic = input + rounding;
			var rounded = roundedWithMagic - rounding;
			var residual = input - rounded;
			var cubicCoefficient = residual * 0.05550361559341535;
			var higherPolynomial = cubicCoefficient + 0.2402284522445722;
			var squared = residual * residual;
			var linear = residual * 0.6931471806916203;
			var higherTerms = higherPolynomial * squared;
			var lowerTerms = linear + 1.0;
			var polynomial = higherTerms + lowerTerms;
			var roundedBits = unchecked((ulong)BitConverter.DoubleToInt64Bits(roundedWithMagic));
			var scaleBits = unchecked((roundedBits << 47) + s_Exp2FloatScale[roundedBits & 31]);
			var scale = BitConverter.Int64BitsToDouble(unchecked((long)scaleBits));
			return (float)(polynomial * scale);
		}

		private static int Log2Byte(byte value)
		{
			var result = 0;
			while (value > 1)
			{
				value >>= 1;
				result++;
			}

			return result;
		}

		private static double EvaluatePolynomial(double[] coefficients, double value)
		{
			var sum = coefficients[coefficients.Length - 1];
			for (var index = coefficients.Length - 2; index >= 0; index--)
			{
				sum *= value;
				sum += coefficients[index];
			}

			return sum;
		}
	}

	/// <summary>
	/// Matches the numeric values and bit flags of FFmpeg's AVRounding enumeration.
	/// </summary>
	[Flags]
	internal enum AvRounding
	{
		Zero = 0,
		Infinity = 1,
		Down = 2,
		Up = 3,
		NearInfinity = 5,
		PassMinMax = 8192
	}
}
